#!/usr/bin/env ruby
# frozen_string_literal: true
# AI-powered blocklist/allowlist reviewer using Ollama + dspy.rb + ruby_llm
#
# Scans all blocklists for mainstream domains that should not be blocked,
# audits all allowlists for suspicious domains that should be blocked,
# and generates allowlists/general_allowlist_from_broad_blocklists.txt.
#
# Usage:
#   ruby scripts/ai_review_blocklists.rb [options]
#
# Options:
#   --host HOST        Ollama host (default: localhost)
#   --port PORT        Ollama port (default: 11434)
#   --model MODEL      Model name (default: mistral)
#   --batch N          Domains per AI batch call (default: 20)
#   --include-large    Include blocklists with >50k domains (slow)
#   --dry-run          Skip writing the output allowlist file

require 'httparty'
require 'json'
require 'set'
require 'optparse'
require 'dspy'
require 'tqdm'

# ── ANSI colour helpers ──────────────────────────────────────────────────────────
module Color
  def self.red(s)    = "\e[31m#{s}\e[0m"
  def self.yellow(s) = "\e[33m#{s}\e[0m"
  def self.green(s)  = "\e[32m#{s}\e[0m"
  def self.cyan(s)   = "\e[36m#{s}\e[0m"
  def self.bold(s)   = "\e[1m#{s}\e[0m"
end

# ── CLI options ──────────────────────────────────────────────────────────────────
options = {
  host:        'localhost',
  port:        11434,
  model:       'mistral',
  batch_size:  20,
  large_limit: 50_000,
  skip_large:  true,
  dry_run:     false,
}

OptionParser.new do |opts|
  opts.banner = "Usage: #{$PROGRAM_NAME} [options]"
  opts.on('--host HOST',     'Ollama host (default: localhost)')            { |v| options[:host]       = v }
  opts.on('--port PORT',     'Ollama port (default: 11434)', Integer)       { |v| options[:port]       = v }
  opts.on('--model MODEL',   'Model name (default: mistral)')               { |v| options[:model]      = v }
  opts.on('--batch N',       'Domains per AI batch (default: 20)', Integer) { |v| options[:batch_size] = v }
  opts.on('--include-large', 'Include blocklists with >50k domains')        { options[:skip_large]     = false }
  opts.on('--dry-run',       "Don't write the output allowlist file")       { options[:dry_run]        = true }
end.parse!

REPO_ROOT        = File.expand_path('../..', __FILE__)
BLOCKLISTS_DIR   = File.join(REPO_ROOT, 'blocklists')
ALLOWLISTS_DIR   = File.join(REPO_ROOT, 'allowlists')
MAIN_SCRIPT      = File.join(REPO_ROOT, 'scripts', 'scrape_malicious_domains.rb')
OUTPUT_ALLOWLIST = File.join(ALLOWLISTS_DIR, 'general_allowlist_from_broad_blocklists.txt')
# Explicitly ignored — it is an exception list generated by extract_ublock_lists.rb
IGNORE_BLOCKLIST = File.realpath(File.join(BLOCKLISTS_DIR, 'ublock', 'allowlist.txt'))

def separator(title = nil)
  puts Color.bold('=' * 62)
  puts Color.bold(title) if title
  puts Color.bold('=' * 62) if title
end

# ── Check Ollama server ──────────────────────────────────────────────────────────
separator
puts Color.bold("AI Blocklist Reviewer — Ollama + dspy.rb + ruby_llm")
separator
puts "Server : http://#{options[:host]}:#{options[:port]}"
puts "Model  : #{options[:model]}"
puts "Batch  : #{options[:batch_size]} domains/call"
puts "Dry run: #{options[:dry_run]}"
puts ""

print "Checking Ollama at #{options[:host]}:#{options[:port]}... "
ollama_models = begin
  resp = HTTParty.get(
    "http://#{options[:host]}:#{options[:port]}/api/tags",
    timeout: 5
  )
  raise "HTTP #{resp.code}" unless resp.code == 200
  JSON.parse(resp.body)['models']&.map { |m| m['name'] } || []
rescue => e
  puts Color.red("FAILED")
  puts Color.red("ERROR: Cannot connect to Ollama — #{e.message}")
  puts Color.red("       Ensure Ollama is running: https://ollama.ai")
  exit 1
end
puts Color.green("OK (#{ollama_models.size} model(s) available)")

model_present = ollama_models.any? { |m| m == options[:model] || m.start_with?("#{options[:model]}:") }
unless model_present
  puts Color.red("ERROR: Model '#{options[:model]}' not found.")
  puts Color.red("       Available: #{ollama_models.join(', ')}")
  puts Color.red("       Pull it with: ollama pull #{options[:model]}")
  exit 1
end
puts Color.green("Model '#{options[:model]}' is available.")

# ── Load SKIP_DOMAINS / EXACT_SKIP_DOMAINS from scrape_malicious_domains.rb ─────
def load_skip_domain_sets(script_path)
  content = File.read(script_path)
  extract = lambda do |const_name|
    m = content.match(/#{Regexp.escape(const_name)}\s*=\s*Set\.new\(%w\[(.*?)\]\s*\)\.freeze/m)
    m ? m[1].split.to_set : Set.new
  end
  [extract.call('SKIP_DOMAINS'), extract.call('EXACT_SKIP_DOMAINS')]
end

skip_domains, exact_skip_domains = load_skip_domain_sets(MAIN_SCRIPT)
puts "\nLoaded #{skip_domains.size} SKIP_DOMAINS + #{exact_skip_domains.size} EXACT_SKIP_DOMAINS from scrape script"

# Replicates the scrape script's skip_domain? logic:
# SKIP_DOMAINS matches root domain AND all subdomains
# EXACT_SKIP_DOMAINS matches only the exact root entry
def in_skip_domains?(domain, skip_domains, exact_skip_domains)
  return true if exact_skip_domains.include?(domain)
  skip_domains.any? { |s| domain == s || domain.end_with?(".#{s}") }
end

# ── Load existing allowlist domains ─────────────────────────────────────────────
def load_list_domains(path)
  return Set.new unless File.exist?(path)
  File.readlines(path, chomp: true)
      .map(&:strip)
      .reject { |l| l.empty? || l.start_with?('#') }
      .to_set
end

allowlist_files = Dir.glob(File.join(ALLOWLISTS_DIR, '**', '*.txt'))
                     .reject { |f| f == OUTPUT_ALLOWLIST }
                     .sort

existing_allowlist_domains = allowlist_files
  .flat_map { |f| load_list_domains(f).to_a }
  .to_set
puts "Loaded #{existing_allowlist_domains.size} domains across #{allowlist_files.size} existing allowlist files"

# ── Configure DSPy with Ollama via ruby_llm adapter ─────────────────────────────
DSPy.configure do |c|
  c.lm = DSPy::LM.new(
    "ruby_llm/#{options[:model]}",
    provider: :ollama,
    base_url: "http://#{options[:host]}:#{options[:port]}/v1",
    structured_outputs: false
  )
end

# ── DSPy Signatures ──────────────────────────────────────────────────────────────

class BlocklistDomainReview < DSPy::Signature
  description <<~DESC
    You are a strict DNS security analyst reviewing domains from a Pi-hole blocklist.
    Your ONLY job is to identify domains that are unambiguously safe and should NOT be blocked.

    ## ALLOW a domain ONLY if ALL of the following are true:
    1. It belongs to a well-known, reputable service (major cloud provider, CDN, developer tool, OS vendor, etc.)
    2. It uses the EXACT canonical TLD for that service (e.g. google.com, not google.pw or google.xyz)
    3. The domain name is spelled correctly with no character substitutions (no 0→o, 1→l, rn→m, etc.)
    4. It is not a subdomain of a suspicious or unknown registrar

    ## BLOCK (do not allow) if ANY of the following are true:
    - The domain uses an unusual or cheap TLD: .pw, .tk, .ml, .ga, .cf, .gq, .xyz, .top, .club, .icu, .buzz, .click, .loan, .win, .bid, .review, .vip, .work, .online (unless the legitimate service is definitively known to use it)
    - The domain visually resembles a brand but is slightly different: googie, g00gle, micosoft, arnazon, paypa1, etc.
    - The domain contains a brand name combined with extra words: google-security.com, amazon-support.net, apple-id-verify.com
    - The domain uses hyphens to sandwich a brand: secure-google-login.com
    - You are uncertain whether this is the real service's domain

    ## STRICT RULES:
    - A domain pretending to be a legitimate brand is MORE dangerous than an unknown domain — reject it
    - "Looks like Google" is NOT sufficient — it must BE Google's actual domain
    - When in doubt, do NOT allow it. False negatives (over-blocking) are far safer than false positives
    - Return ONLY domain names from the input list, one per line, no explanation

    Input domains:
  DESC

  input do
    const :domains,  String, description: 'Newline-separated list of domains to review'
    const :context,  String, description: 'Blocklist filename providing context for these domains'
  end

  output do
    const :allow_domains, String,
          description: 'Newline-separated domains from the input that should be ALLOWED. Empty string if none.'
    const :reasoning, String,
          description: 'Brief explanation of the decisions made'
  end
end

class AllowlistDomainAudit < DSPy::Signature
  description <<~DESC
    You are a DNS security expert auditing a Pi-hole allowlist (whitelist).
    Your task: identify any domains that seem suspicious, malicious, or inappropriate to allow.
    Flag a domain if it appears to be a malware C2 server, phishing site, ad/tracker network,
    cryptominer, or otherwise not a legitimate mainstream service.
    Be conservative — only flag domains with clear red flags.
    Return only domain names that were in the input list.
  DESC

  input do
    const :domains,  String, description: 'Newline-separated list of allowlisted domains to audit'
    const :context,  String, description: 'Allowlist filename providing context'
  end

  output do
    const :suspicious_domains, String,
          description: 'Newline-separated domains from the input that seem suspicious and should be BLOCKED. Empty string if none.'
    const :reasoning, String,
          description: 'Brief explanation of any concerns found'
  end
end

# ── AI helper methods ────────────────────────────────────────────────────────────
blocklist_reviewer = DSPy::Predict.new(BlocklistDomainReview)
allowlist_auditor  = DSPy::Predict.new(AllowlistDomainAudit)

IPV4_RE = /\A(\d{1,3}\.){3}\d{1,3}\z/
IPV6_RE = /\A[0-9a-fA-F:]+\z/

def ip_address?(str)
  IPV4_RE.match?(str) || (str.include?(':') && IPV6_RE.match?(str))
end

def parse_domain_response(str)
  str.to_s
     .split(/[\n,]+/)
     .map(&:strip)
     .reject(&:empty?)
     .map { |d| d.downcase.gsub(/\A[*.\s]+|[.\s]+\z/, '') }
     .reject { |d| d.include?(' ') || !d.include?('.') || ip_address?(d) }
end

VALIDATION_ERROR_PATTERNS = [
  'Missing required prop',
  'Prediction validation failed',
  'Failed to parse LLM response as JSON',
].freeze

def ai_call_error(e)
  msg = e.message.to_s
  # Validation/parse failures just mean the model returned unstructured text — skip silently
  return if VALIDATION_ERROR_PATTERNS.any? { |p| msg.include?(p) }
  warn Color.yellow("    [AI ERROR] #{msg}")
end

def ai_review_blocklist_batch(reviewer, domains, context)
  result = reviewer.call(domains: domains.join("\n"), context: context)
  # Filter to only return domains that were actually in the input batch
  input_set = domains.map(&:downcase).to_set
  parse_domain_response(result.allow_domains).select { |d| input_set.include?(d) }
rescue => e
  ai_call_error(e)
  []
end

def ai_audit_allowlist_batch(auditor, domains, context)
  result = auditor.call(domains: domains.join("\n"), context: context)
  input_set = domains.map(&:downcase).to_set
  parse_domain_response(result.suspicious_domains).select { |d| input_set.include?(d) }
rescue => e
  ai_call_error(e)
  []
end

# ── Scan blocklists ──────────────────────────────────────────────────────────────
separator("BLOCKLIST REVIEW")
puts ""

blocklist_files = Dir.glob(File.join(BLOCKLISTS_DIR, '**', '*.txt'))
                     .reject { |f|
                       begin
                         File.realpath(f) == IGNORE_BLOCKLIST
                       rescue
                         false
                       end
                     }
                     .sort

all_domains_to_allow   = Set.new
total_sanity_flags     = 0
blocklist_sanity_flags = Hash.new { |h, k| h[k] = [] }

blocklist_files.each do |bfile|
  rel     = bfile.sub("#{REPO_ROOT}/", '')
  domains = load_list_domains(bfile).to_a.sort
  next if domains.empty?

  if options[:skip_large] && domains.size > options[:large_limit]
    puts "#{Color.cyan(rel)} (#{domains.size} domains)"
    puts Color.yellow("  SKIPPED — too large (>#{options[:large_limit]}). Use --include-large to process.")
    puts ""
    next
  end

  puts "#{Color.cyan(rel)} (#{domains.size} domains)"

  # ── Sanity check: domain appears in both blocklist and known-safe lists ────
  domains.each do |domain|
    in_skip  = in_skip_domains?(domain, skip_domains, exact_skip_domains)
    in_allow = existing_allowlist_domains.include?(domain)

    if in_skip || in_allow
      source = in_allow ? 'existing allowlist' : (exact_skip_domains.include?(domain) ? 'EXACT_SKIP_DOMAINS' : 'SKIP_DOMAINS')
      msg = "  #{domain}  (also in #{source})"
      puts Color.yellow("  [SANITY] #{msg}")
      blocklist_sanity_flags[rel] << msg
      total_sanity_flags += 1
    end
  end

  # ── AI review — only domains not already known-safe, and not IPs ─────────
  reviewable = domains.reject do |d|
    ip_address?(d) ||
      in_skip_domains?(d, skip_domains, exact_skip_domains) ||
      existing_allowlist_domains.include?(d)
  end

  if reviewable.empty?
    puts "  All domains covered by SKIP_DOMAINS / existing allowlists — no AI review needed."
    puts ""
    next
  end

  batches = reviewable.each_slice(options[:batch_size]).to_a
  puts "  AI reviewing #{reviewable.size} domains..."
  batches.tqdm(desc: "  #{File.basename(bfile)}", unit: 'batch', leave: true).each do |batch|
    allowed = ai_review_blocklist_batch(blocklist_reviewer, batch, rel)
    next unless allowed.any?
    allowed.each { |d| all_domains_to_allow.add(d) }
    allowed.each { |d| puts Color.green("  + #{d}") }
  end
  puts ""
end

# ── Audit allowlists ─────────────────────────────────────────────────────────────
separator("ALLOWLIST AUDIT")
puts ""

suspicious_by_file = Hash.new { |h, k| h[k] = [] }

allowlist_files.each do |afile|
  next if afile == OUTPUT_ALLOWLIST
  rel     = afile.sub("#{REPO_ROOT}/", '')
  domains = load_list_domains(afile).to_a.sort.reject { |d| ip_address?(d) }
  next if domains.empty?

  batches = domains.each_slice(options[:batch_size]).to_a
  puts "#{Color.cyan(rel)} (#{domains.size} domains)"
  batches.tqdm(desc: "  #{File.basename(afile)}", unit: 'batch', leave: true).each do |batch|
    suspicious = ai_audit_allowlist_batch(allowlist_auditor, batch, rel)
    next unless suspicious.any?
    suspicious_by_file[rel].concat(suspicious)
    suspicious.each { |d| puts Color.red("  ! #{d}") }
  end
  puts ""
end

# ── Write output allowlist ───────────────────────────────────────────────────────
separator("OUTPUT")
puts ""

# Exclude domains already in existing allowlists
new_allow_domains = (all_domains_to_allow.to_a - existing_allowlist_domains.to_a).sort

puts "Domains AI flagged for allowlist : #{all_domains_to_allow.size}"
puts "Already in existing allowlists   : #{all_domains_to_allow.size - new_allow_domains.size}"
puts "New domains to write             : #{new_allow_domains.size}"
puts ""

unless options[:dry_run]
  File.open(OUTPUT_ALLOWLIST, 'w') do |f|
    f.puts "# AI-Generated Allowlist from Broad Blocklist Review"
    f.puts "# Generated : #{Time.now.utc.strftime('%Y-%m-%dT%H:%M:%SZ')}"
    f.puts "# Model     : #{options[:model]} @ #{options[:host]}:#{options[:port]}"
    f.puts "# Blocklists: #{blocklist_files.map { |b| b.sub("#{REPO_ROOT}/", '') }.join(', ')}"
    f.puts "#"
    f.puts "# These domains were identified by AI as legitimate mainstream services"
    f.puts "# found in broad blocklists. Review carefully before deploying to Pi-hole."
    f.puts ""
    new_allow_domains.each { |d| f.puts d }
  end
  puts Color.green("Wrote #{new_allow_domains.size} domains to #{OUTPUT_ALLOWLIST.sub("#{REPO_ROOT}/", '')}")
else
  puts Color.yellow("[DRY RUN] Would write #{new_allow_domains.size} domains — skipped.")
  new_allow_domains.each { |d| puts "  #{d}" } if new_allow_domains.any?
end

# ── Summary ──────────────────────────────────────────────────────────────────────
separator("SUMMARY")
puts ""

total_suspicious = suspicious_by_file.values.sum(&:size)

puts "Blocklists reviewed       : #{blocklist_files.size}"
puts "Allowlists audited        : #{allowlist_files.reject { |f| f == OUTPUT_ALLOWLIST }.size}"
puts "Sanity flags              : #{total_sanity_flags > 0 ? Color.yellow(total_sanity_flags.to_s) : '0'}"
puts "Domains flagged to allow  : #{all_domains_to_allow.size > 0 ? Color.green(all_domains_to_allow.size.to_s) : '0'}"
puts "Suspicious allowlist hits : #{total_suspicious > 0 ? Color.red(total_suspicious.to_s) : '0'}"

if total_sanity_flags > 0
  puts ""
  puts Color.yellow("SANITY FLAG DETAILS (domain in both blocklist and skip/allowlist):")
  blocklist_sanity_flags.each do |file, flags|
    next if flags.empty?
    puts Color.yellow("  #{file}:")
    flags.each { |f| puts Color.yellow("    #{f}") }
  end
end

if total_suspicious > 0
  puts ""
  puts Color.red("SUSPICIOUS ALLOWLIST ENTRIES (review these!):")
  suspicious_by_file.each do |file, doms|
    next if doms.empty?
    puts Color.red("  #{file}:")
    doms.each { |d| puts Color.red("    - #{d}") }
  end
end

puts ""
puts "Done."
